export const dummy = {
    dates: { maximum: '2023-06-24', minimum: '2023-05-07' },
    page: 1,
    results: [
        {
            adult: false,
            backdrop_path: '/e2Jd0sYMCe6qvMbswGQbM0Mzxt0.jpg',
            genre_ids: [28, 80, 53],
            id: 385687,
            original_language: 'en',
            original_title: 'Fast X',
            overview:
                '돔과 그의 패밀리 앞에 나타난 운명의 적 단테. 과거의 그림자는 돔의 모든 것을 파괴하기 위해 달려온다. 단테에 의해 산산히 흩어진 패밀리들은 모두 목숨을 걸고 맞서야 하는 함정에 빠지고 마는데...',
            popularity: 6963.783,
            poster_path: '/wXNihLltMCGR7XepN39syIlCt5X.jpg',
            release_date: '2023-05-17',
            title: '분노의 질주: 라이드 오어 다이',
            video: false,
            vote_average: 7.3,
            vote_count: 1998,
        },
        {
            adult: false,
            backdrop_path: '/nGxUxi3PfXDRm7Vg95VBNgNM8yc.jpg',
            genre_ids: [28, 12, 16, 878],
            id: 569094,
            original_language: 'en',
            original_title: 'Spider-Man: Across the Spider-Verse',
            overview:
                '여러 성장통을 겪으며 새로운 스파이더맨이 된 마일스 모랄레스. 그 앞에 다른 평행세계의 스파이더우먼 그웬이 다시 나타난다. 모든 차원의 멀티버스 속 스파이더맨들을 만나게 되지만, 질서에 대한 신념이 부딪히며 예상치 못한 균열이 생기는데… 상상 그 이상을 넘어서는 멀티버스의 세계가 열린다!',
            popularity: 2550.738,
            poster_path: '/zG9TYiHt0fdaJiWuNEhFrfKzwoi.jpg',
            release_date: '2023-06-21',
            title: '스파이더맨: 어크로스 더 유니버스',
            video: false,
            vote_average: 8.6,
            vote_count: 1675,
        },
        {
            adult: false,
            backdrop_path: '/9NgtktUFLm9cnFDFaekx2ROh84f.jpg',
            genre_ids: [28, 12, 878],
            id: 667538,
            original_language: 'en',
            original_title: 'Transformers: Rise of the Beasts',
            overview:
                '전 우주의 행성을 집어삼키는 절대자, ‘유니크론’의 부하 ‘스커지’는 ‘테러콘’들을 이끌고 지구에 당도한다. 그에 맞서기 위해 지구에 정체를 숨기고 있던 트랜스포머 ‘오토봇’ 군단이 모습을 드러내고 또 다른 트랜스포머 진영인 ‘맥시멀’과 힘을 합친다. 옵티머스 프라임이 이끄는 ‘오토봇’과 옵티머스 프라이멀을 중심으로 한 ‘맥시멀’. 모두의 운명을 건 그들의 압도적 전투가 시작된다!',
            popularity: 2094.924,
            poster_path: '/chUZNPNd7EiETSB4xBGykXhuXRr.jpg',
            release_date: '2023-06-06',
            title: '트랜스포머: 비스트의 서막',
            video: false,
            vote_average: 7.2,
            vote_count: 419,
        },
        {
            adult: false,
            backdrop_path: '/7e9MVGg8efOhoA2R9XhZcGWTC5Z.jpg',
            genre_ids: [878, 28, 12],
            id: 298618,
            original_language: 'en',
            original_title: 'The Flash',
            overview:
                '시공간이 붕괴된 세계, 차원이 다른 히어로가 온다! 빛보다 빠른 스피드, 물체 투과, 전기 방출, 자체 회복, 천재적인 두뇌까지 갓벽한 능력을 자랑하지만 존재감은 제로, 저스티스 리그에서 궂은일을 도맡아 하는 히어로 ‘플래시’. 어느 날 자신에게 빛보다 빠른 속도로 달리면 시공간 이동 능력이 있음을 알게 된 그는 ‘브루스 웨인’의 만류를 무시한 채 끔찍한 상처로 얼룩진 과거를 바꾸기 위해 시간을 역행한다. 의도치 않은 장소에 불시착한 ‘플래시’는 멀티버스 세상 속 또 다른 자신과 맞닥뜨리고 메타 휴먼이 흔적도 없이 사라지고 모든 것이 뒤엉킨 세상과 마주하게 된다. ‘플래시’는 자신이 알던 모습과 전혀 달라진 나이 들고 은퇴한 ‘배트맨’과 크립톤 행성에서 온 ‘슈퍼걸’의 도움으로 외계의 침공으로부터 시간과 차원이 붕괴된 지구를 구하려 나서는데…',
            popularity: 1354.359,
            poster_path: '/muD7qu9UagO08dZBout1YXwdE6a.jpg',
            release_date: '2023-06-14',
            title: '플래시',
            video: false,
            vote_average: 6.8,
            vote_count: 581,
        },
        {
            adult: false,
            backdrop_path: '/cSYLX73WskxCgvpN3MtRkYUSj1T.jpg',
            genre_ids: [16, 35, 10751, 14, 10749],
            id: 976573,
            original_language: 'en',
            original_title: 'Elemental',
            overview:
                '불, 물, 공기, 흙 4개의 원소들이 살고 있는 엘리멘트 시티. 재치 있고 불처럼 열정 넘치는 앰버는 어느 날 우연히 유쾌하고 감성적이며 물 흐르듯 사는 웨이드를 만나 특별한 우정을 쌓으며, 지금껏 믿어온 모든 것들이 흔들리는 새로운 경험을 하게 되는데...',
            popularity: 1410.702,
            poster_path: '/1YYL1OcgjPLjAGi6n0iZe1gdl9i.jpg',
            release_date: '2023-06-14',
            title: '엘리멘탈',
            video: false,
            vote_average: 7.5,
            vote_count: 147,
        },
        {
            adult: false,
            backdrop_path: '/ribiMu3iINPxDkofErPxe8jQ8L0.jpg',
            genre_ids: [12, 10751, 14, 10749],
            id: 447277,
            original_language: 'en',
            original_title: 'The Little Mermaid',
            overview:
                '아틀란티카 바다의 왕 트라이튼의 사랑스러운 막내딸인 인어 에리얼은 늘 인간들이 사는 바다 너머 세상으로의 모험을 꿈꾼다. 어느 날, 우연히 바다 위로 올라갔다가 폭풍우 속 가라앉는 배에 탄 인간 에릭 왕자의 목숨을 구해준다. 갈망하던 꿈과 운명적인 사랑을 이루기 위해 용기를 낸 에리얼은 사악한 바다 마녀 울슐라와의 위험한 거래를 통해 다리를 얻게 된다. 드디어 바다를 벗어나 그토록 원하던 인간 세상으로 가게 되지만, 그 선택으로 에리얼과 아틀란티카 왕국 모두 위험에 처하게 되는데… 바닷속, 그리고 그 너머 아름다운 꿈과 사랑의 멜로디가 펼쳐진다!',
            popularity: 1241.627,
            poster_path: '/8k8tmcx5e6ShpackLnDswBo1tnB.jpg',
            release_date: '2023-05-24',
            title: '인어공주',
            video: false,
            vote_average: 6.2,
            vote_count: 746,
        },
        {
            adult: false,
            backdrop_path: '/2EL6QrQmUt2ntBXjuHO4KsEfaoU.jpg',
            genre_ids: [27, 53],
            id: 758323,
            original_language: 'en',
            original_title: "The Pope's Exorcist",
            overview:
                "바티칸이 인정한 공식 수석 엑소시스트이자 최고의 구마사제 '가브리엘 아모르트’ 신부(러셀 크로우)는 한 어린 소년에게 들린 악마를 구마하기 위해 스페인으로 향한다. 그리고 그곳에서 바티칸이 숨겨온 충격적인 비밀과 마주하고, '토마스 에스퀴벨’ 신부(다니엘 조바토)와 함께 진실을 파헤치게 되는데...",
            popularity: 828.419,
            poster_path: '/fA1xRPplBqW87wWh0hO1pwbQmX8.jpg',
            release_date: '2023-05-10',
            title: '엑소시스트: 더 바티칸',
            video: false,
            vote_average: 7.2,
            vote_count: 1463,
        },
        {
            adult: false,
            backdrop_path: '/xRasrVcMrkCK2gcIJRERDBmjQHo.jpg',
            genre_ids: [27, 9648, 53],
            id: 934433,
            original_language: 'en',
            original_title: 'Scream VI',
            overview:
                '고스트페이스의 습격에서 살아남은 생존자들이 우즈보로를 떠나 뉴욕에서 새로운 삶을 시작하지만, 다시금 과거의 살인마에게 쫓기게 되는 이야기',
            popularity: 460.008,
            poster_path: '/1zhb49U0Rjg2qVU9L7VLmujf1Hs.jpg',
            release_date: '2023-05-24',
            title: '스크림 6',
            video: false,
            vote_average: 7.3,
            vote_count: 1411,
        },
        {
            adult: false,
            backdrop_path: '/qElNES0sHVQcbzvGrTx7ccpGzij.jpg',
            genre_ids: [878, 28, 18],
            id: 842675,
            original_language: 'zh',
            original_title: '流浪地球2',
            overview:
                '태양계 소멸의 위기를 맞은 인류는 지구 표면에 거대한 엔진을 달아 궤도를 옮기는 ‘유랑지구 프로젝트’에 돌입한다. 하지만, 데이터베이스로 영생을 가지려는 ‘디지털 라이프’와 대립하게 되며 프로젝트는 난관에 부딪히게 되고, 그 과정 속 달과의 충돌이라는 예상치 못한 대재앙에 놓이게 되는데… 살아남기 위한 선택은 단 하나, 달을 파괴하라!',
            popularity: 493.139,
            poster_path: '/pajq0n6FZivirCg1ifpe4zYKvsA.jpg',
            release_date: '2023-05-10',
            title: '유랑지구 2',
            video: false,
            vote_average: 7.2,
            vote_count: 272,
        },
        {
            adult: false,
            backdrop_path: '/sp7MPK2K60LLd7A6zjHKsfgjFil.jpg',
            genre_ids: [27, 14, 878, 53],
            id: 296271,
            original_language: 'en',
            original_title: 'The Devil Conspiracy',
            overview:
                '토리노 박물관에서 전시 중이던 예수 그리스도의 시신을 감쌌던 수의가 강탈되는 장면을 목격하면서 미국에서 유학 온 예술대 학생 로라의 운명이 참극으로 치닫게 된다. 로라에게 착상한 생명은 사탄인가, 재림 예수인가?',
            popularity: 188.528,
            poster_path: '/AdkReuLR9vumTzuFGTl9UBkpLTN.jpg',
            release_date: '2023-06-08',
            title: '악마의 부활',
            video: false,
            vote_average: 6.3,
            vote_count: 186,
        },
        {
            adult: false,
            backdrop_path: '/uH1cuq2hmZn5B4oiR9a1l4Wy91I.jpg',
            genre_ids: [35, 28, 18, 12],
            id: 931102,
            original_language: 'zh',
            original_title: '龙马精神',
            overview:
                '한때 잘 나갔던 전설의 스턴트맨 ‘루오’(성룡). 유일한 파트너마 ‘레드 헤어’가 경매에 부쳐질 위기에 처하자 어쩔 수 없이 소원했던 딸 ‘바오’(류호존)에게 연락해 도움을 청한다. ‘바오’는 자신의 변호사 남자친구 ‘미키’(곽기린)와 이를 해결하고자 하고, 조금씩 ‘루오’에게도 마음을 열어간다. 그러던 어느 날, ‘루오’가 ‘레드 헤어’를 지키기 위해 싸웠던 콤비 액션 영상이 SNS를 통해 화제를 모으게 되고, 유명 영화에 참여할 기회까지 찾아오는데…! 스턴트 생활을 청산하길 바라는 딸 ‘바오’와 인생 역전의 기회에서 고민하는 ‘루오’. 과연, 그는 가족과 커리어를 모두 지킬 수 있을 것인가?!',
            popularity: 214.871,
            poster_path: '/8Rnnx17kOFL4mNchdJNzLSdlBZj.jpg',
            release_date: '2023-05-31',
            title: '라이드 온',
            video: false,
            vote_average: 7,
            vote_count: 62,
        },
        {
            adult: false,
            backdrop_path: '/kgATFkG4SDyengNMmCuwmj7igWW.jpg',
            genre_ids: [14, 28, 12],
            id: 455476,
            original_language: 'en',
            original_title: 'Knights of the Zodiac',
            overview:
                '강력한 힘을 가진 전쟁과 지혜의 신 ‘아테나’의 환생! 세상을 구할 수호 기사가 깨어난다!  어린 시절 누나 ‘패트리샤’가 납치된 후 홀로 자란 ‘세이야’  슬럼가 지하 격투장에서 벌어지는 결투로 근근이 살아가던 중, 위기의 상황에서 자신도 알지 못했던 미스터리한 힘이 발현되면서 ‘아테나’를 찾고 있던 ‘구라드’의 무장 조직에게 쫓기게 된다.  수수께끼의 남자 ‘알먼 키도’에 의해 가까스로 목숨을 구한 ‘세이야’는 그를 따라 도착한 은신처에서 ‘아테나’의 환생인 ‘시에나’와 마주한다.  오래전, 다른 신들에 맞서 인간을 지키던 전쟁과 지혜의 신 ‘아테나’ ‘알먼 키도’는 ‘시에나’에게 잠재된 ‘아테나’의 힘이 곧 깨어날 것이며, ‘세이야’는 ‘아테나’를 수호하고 세상을 지킬 성투사의 운명을 가졌다는 사실을 알려주는데...',
            popularity: 177.065,
            poster_path: '/fBNl8kpFMz5ugi3RGYfenKctzjq.jpg',
            release_date: '2023-05-31',
            title: '세인트 세이야: 더 비기닝',
            video: false,
            vote_average: 6.2,
            vote_count: 68,
        },
        {
            adult: false,
            backdrop_path: '/mK0a3t62lM8ho3mmvBWf6NxdWvw.jpg',
            genre_ids: [27, 9648, 14],
            id: 532408,
            original_language: 'en',
            original_title: 'The Boogeyman',
            overview:
                '‘세이디’와 어린 동생 ‘소여’는 갑작스러운 엄마의 사고로 깊은 슬픔에 빠진다. 그러던 어느날, 낯선 남자가 집에 찾아온 뒤부터 어둠 속에서 알 수 없는 존재가 나타나기 시작하는데… 6월 6일, 공포의 문이 열린다!',
            popularity: 103.088,
            poster_path: '/8qaKUHcTD4T2Xs43Y4MwvIKXnKb.jpg',
            release_date: '2023-06-06',
            title: '부기맨',
            video: false,
            vote_average: 6.4,
            vote_count: 98,
        },
        {
            adult: false,
            backdrop_path: '/isGINC82PZmMblEJP2rBAvSlX37.jpg',
            genre_ids: [16, 10751, 12, 35],
            id: 599019,
            original_language: 'ru',
            original_title: 'Большое путешествие. Специальная доставка',
            overview:
                '아기 팬더를 배달한 게 엊그제 같은데, 이번엔 아기 반달곰이 뚝! 떨어졌다. 그런데 무려, 동물왕국 대통령 후보의 아들이라고?! ‘믹믹’과 ‘오스카’는 동물왕국의 평화를 위해, 다시 한번 아기를 배달하기로 결심한다. 애니멀 특송단, 배달 시작합니다!',
            popularity: 86.559,
            poster_path: '/t4KQRvKUsRTw66cRiGD2w65oKdo.jpg',
            release_date: '2023-05-27',
            title: '빅트립2: 아기곰 배달 대작전',
            video: false,
            vote_average: 6.5,
            vote_count: 72,
        },
        {
            adult: false,
            backdrop_path: '/jENycYiYGr5NvMs789zj06JkW5l.jpg',
            genre_ids: [35, 18],
            id: 497828,
            original_language: 'en',
            original_title: 'Triangle of Sadness',
            overview:
                '호화 크루즈에 협찬으로 승선한 인플루언서 모델 커플. 각양각색의 부자들과 휴가를 즐기던 사이, 뜻밖의 사건으로 배가 전복되고 8명만이 간신히 무인도에 도착한다. 할 줄 아는 거라곤 구조 대기뿐인 사람들. 이때 존재감을 드러내는 건...',
            popularity: 67.255,
            poster_path: '/ltEblZr0pwTf585kbrZSWyNf4uj.jpg',
            release_date: '2023-05-17',
            title: '슬픔의 삼각형',
            video: false,
            vote_average: 7.2,
            vote_count: 1418,
        },
        {
            adult: false,
            backdrop_path: '/xH1fADDlEQMXreGClUCxA0XrJPC.jpg',
            genre_ids: [35, 10749],
            id: 982271,
            original_language: 'en',
            original_title: 'Book Club: The Next Chapter',
            overview:
                '한동안 세상이 멈추면서 만나지 못했던 북 클럽 4인방. 오랜만에 다시 모인 자리에서 비비안이 약혼 소식을 전하고 그런 비비안을 위한 싱글파티의 일환으로 이탈리아 여행을 계획한다. 로마부터 베니스까지, 불타는 청춘 못지 않게 여행하던 이들은 비비안이 주인공인 중요한 일정을 위해 마지막 여행지인 토스카나로 향한다. 그러나 이들 앞에 예상치 못한 일이 벌어지면서 발이 묶이는 위기에 처하는데…',
            popularity: 70.928,
            poster_path: '/mKjr1fRB6hjVi2XISVEmp5SVRIy.jpg',
            release_date: '2023-06-07',
            title: '북 클럽: 넥스트 챕터',
            video: false,
            vote_average: 6.8,
            vote_count: 58,
        },
        {
            adult: false,
            backdrop_path: '/qHurP5rHZk63ZIcjegKy1M57oC7.jpg',
            genre_ids: [35, 9648, 28],
            id: 983883,
            original_language: 'zh',
            original_title: '關於我和鬼變成家人的那件事',
            overview:
                "혈기왕성한 형사 우밍한은 중요한 사건 현장에서 도로에 흩어진 증거물을 수집하던 중 의문의 붉은 봉투를 발견하고 무심코 줍는다. 그때부터 밍한에게 벌어지는 불길한 사건들! 자신에게 다가온 '운명'을 한사코 거부하던 밍한은 거듭되는 생명의 위협에 마지못해 인생 최대의 결심을 하는데... 얼결에 '부부'가 된 귀신과 최악의 빌런을 잡기 위해 인간+귀신 콤비가 벌이는 극강의 공조 수사! 코믹과 액션을 버무리고 감동과 반전까지 가미한, 풀옵션 오감으로 즐기는 블록버스터. 인류애 넘치는 콤비의 격정적인 공조가 마침내 시작된다! 이 콤비도, 두 사람의 공조 수사도 완전히 다 미쳤다!!!",
            popularity: 45.88,
            poster_path: '/m9UIiiTDTx6w1gPQgVr8cvgol91.jpg',
            release_date: '2023-05-17',
            title: '메리 마이 데드 바디',
            video: false,
            vote_average: 6.7,
            vote_count: 9,
        },
        {
            adult: false,
            backdrop_path: '/4uij4drUitClyXihCyQJSklXvvv.jpg',
            genre_ids: [18, 10749],
            id: 876797,
            original_language: 'ja',
            original_title: '余命10年',
            overview:
                '스무 살이 되던 해, 수 만명 중 1명이 걸리는 난치병으로 10년의 삶을 선고받은 ‘마츠리’는 삶의 의지를 잃은 ‘카즈토’를 만나 사랑에 빠진다. 처음 만난 봄, 즐거운 여름, 아름답던 가을, 깊어진 겨울까지 하루하루 애틋하게 사랑한 두 사람 하지만 쌓이는 추억만큼 줄어드는 시간 앞에 결국 ‘마츠리’는 ‘카즈토’를 떠나기로 결심하는데…',
            popularity: 64.566,
            poster_path: '/y2Ucvit19UUfsdLKlYyDz2ZfToS.jpg',
            release_date: '2023-05-24',
            title: '남은 인생 10년',
            video: false,
            vote_average: 7,
            vote_count: 35,
        },
        {
            adult: false,
            backdrop_path: '/fRrpOILyXuWaWLmqF7kXeMVwITQ.jpg',
            genre_ids: [27, 28, 12],
            id: 522444,
            original_language: 'en',
            original_title: 'Black Water: Abyss',
            overview:
                '호주의 깊은 숲 속. 외딴 동굴 탐험에 나선 제니퍼와 에릭, 그리고 친구들은 폭풍우로 인해 불어난 물로 동굴에 갇히게 된다.  제한된 식량과 시간 속에서 탈출구를 찾던 그들에게 불길한 그림자가 서서히 드리우는데...  미로처럼 뻗어 나가는 동굴 속  그들은 과연 살아서 동굴을 탈출할 수 있을까?',
            popularity: 65.55,
            poster_path: '/8nYyl8WJE9BXPaBsjZglzJo36FP.jpg',
            release_date: '2023-06-14',
            title: '블랙 워터: 어비스',
            video: false,
            vote_average: 5.2,
            vote_count: 386,
        },
        {
            adult: false,
            backdrop_path: '/vblTCXOWUQGSc837vgbhDRi4HSc.jpg',
            genre_ids: [80, 28],
            id: 955555,
            original_language: 'ko',
            original_title: '범죄도시3',
            overview:
                '베트남 납치 살해범 검거 후 7년 뒤, 마석도는 새로운 팀원들과 함께 살인사건을 조사한다. 사건 조사 중, 마석도는 신종 마약 사건이 연루되었음을 알게 되고 수사를 확대한다. 한편, 마약 사건의 배후인 주성철은 계속해서 판을 키워가고 약을 유통하던 일본 조직과 리키까지 한국에 들어오며 사건의 규모는 점점 더 커져가는데...',
            popularity: 48.795,
            poster_path: '/jbremGnsRR4XZMDj97YHt20isRP.jpg',
            release_date: '2023-05-31',
            title: '범죄도시3',
            video: false,
            vote_average: 6.1,
            vote_count: 37,
        },
    ],
    total_pages: 5,
    total_results: 98,
};
